### PR TITLE
upgrade superagent-proxy to fix security vulnerability

### PR DESCRIPTION
**Pull request by mattcasey**
I get a severe security warning when installing this module due to a MitM vulnerability. It's fixed by updating superagent-proxy to v3. From what I can tell, there was a chain of dependencies that got updated (see my output of npm audit below).

 I did not test the update, but here's the relevant PR where they bumped the version: https://github.com/TooTallNate/superagent-proxy/issues/40

```
# npm audit report

pac-resolver  <5.0.0
Severity: high
Code Injection - https://npmjs.com/advisories/1784
No fix available
node_modules/pac-resolver
  pac-proxy-agent  <=4.1.0
  Depends on vulnerable versions of pac-resolver
  node_modules/pac-proxy-agent
    proxy-agent  1.1.0 - 4.0.1
    Depends on vulnerable versions of pac-proxy-agent
    node_modules/proxy-agent
      superagent-proxy  0.4.0 - 2.1.0
      Depends on vulnerable versions of proxy-agent
      node_modules/superagent-proxy
        pubnub  >=4.4.1
        Depends on vulnerable versions of superagent-proxy
        node_modules/pubnub
          pubnub-react  *
          Depends on vulnerable versions of pubnub
          node_modules/pubnub-react
```

### CODE REVIEW

**Comment by zymotik** [comment]
From the [travis build log](https://app.travis-ci.com/github/pubnub/javascript/builds/239109342):
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/raipubnub/gulp-istanbul.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

Is this a transient error? Can a new build be triggered? Any ideas? Please, we are depending on this fix.

**Comment by puopg** [comment]
@raipubnub Hey would you mind giving us an update on the status of this fix? Is there a ticket/issue open to follow in the affected packages? 

We are also concerned since Snyk has flagged this as an issue.

**Comment by raipubnub** [comment]
@puopg  The superagent upgrade testing was recently completed and will be released very soon.

**Comment by raipubnub** [comment]
This is released in version 4.34.0 and should clear up and vulnerability warnings caused by superagent-proxy.

**Pull request closed without merging**
