### PR TITLE
CLEN-1406/Fix proxy agent dependency upgrade

### PR DESCRIPTION
**Pull request by mohitpubnub**
fix: remove dependency from superagent-proxy.

Fixes issue of severe vulnerability warnings for vm2 usage.

### CODE REVIEW

**Review by parfeon — APPROVED** [review]
LGTM!

**Comment by wesleysiqueira** [comment]
Please Merge this!!

**Comment by mohitpubnub** [comment]
@pubnub-release-bot release as v7.3.3

**Review by techwritermat — APPROVED** [review]

**Comment by parfeon** [comment]
@pubnub-release-bot release as v7.3.0

**Pull request merged**
