### PR TITLE
ref/memberships

### PR DESCRIPTION
**Pull request by mohitpubnub**
feat: Added membership apis

Added user and space memberships related methods.

feat: Added `type` and `status` fields.

Added `type` and `status` fields in `User` and `Space`. `status` field in memberships.

### CODE REVIEW

**Comment by mohitpubnub** [comment]
WiP `fetchMemberships`

**Comment by are** [comment]
Oh, you have to remember that we cannot remove or change any existing methods. (the remove -> delete should be fine)

**Comment by mohitpubnub** [comment]
> Oh, you have to remember that we cannot remove or change any existing methods. (the remove -> delete should be fine)

Yes,
apart from that it has following changes
- `status` field in membership api's patch payload.
- `if (params?.limit))`  returns false with integer 0 param value of `limit` which we set default with add/update memberships. So it has to check for `null`

**Review by are — APPROVED** [review]

**Review by are — APPROVED** [review]

**Review by are — APPROVED** [review]

**Comment by mohitpubnub** [comment]
@client-engineering-bot release as v7.1.1

**Review by kazydek — APPROVED** [review]

**Pull request merged**
