### PR TITLE
Don't set body content for a GET request on NativeScript

### PR DESCRIPTION
**Pull request by thomasconner**
Setting the body for a `GET` request made with an Android app on [NativeScript](https://www.nativescript.org) results in the following error:

```
System.err: java.net.ProtocolException: method does not support a request body: GET
System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
System.err:     at org.nativescript.widgets.Async$Http$RequestOptions.writeContent(Async.java:313)
System.err:     at org.nativescript.widgets.Async$Http$HttpRequestTask.doInBackground(Async.java:536)
System.err:     at org.nativescript.widgets.Async$Http$1.run(Async.java:482)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
System.err:     at org.nativescript.widgets.Async$PriorityThreadFactory$1.run(Async.java:52)
System.err:     at java.lang.Thread.run(Thread.java:764)
```

The `method` is now checked before setting the body on the `httpConfig` to prevent this error.

### CODE REVIEW

**Comment by thomasconner** [comment]
@MaxPresman Can this get reviewed? Not sure who to call out so I chose you 😄

**Comment by thomasconner** [comment]
@ManuelFernando Including you since you helped get my last PR merged.

**Comment by thomasconner** [comment]
@ManuelFernando Can you take a look at this PR and see if it can be merged?

**Comment by ManuelFernando** [comment]
@thomasconner I’m concerned with your PR because if you remove content: body, this will affect to POST request, is it only this change?, for future PR please does to develop branch

**Comment by ManuelFernando** [comment]
but I have an idea to resolve this, I’ll create a new PR over develop and send you

**Comment by ManuelFernando** [comment]
@thomasconner I just checked again and appear ok, can you create a new PR over develop only with changes in /src

**Comment by ManuelFernando** [comment]
@thomasconner or if you want to, I can add your code, pls let me know!

**Comment by ManuelFernando** [comment]
@thomasconner, it was introduced your changes into the version 4.21.6 which one will be release very soon

**Comment by thomasconner** [comment]
@ManuelFernando Somehow I missed this but I see now that I should use the develop branch for future PRs. Thanks for adding the change

**Pull request closed without merging**
