### PR TITLE
Use null instead of '' for NativeScript Networking Module

### PR DESCRIPTION
**Pull request by thomasconner**
Remove the use of 

```
if (method !== 'GET') {
    httpConfig.content = body;
}
```

 and instead pass `null` instead of `''` to the `body` parameter.

### CODE REVIEW

**Comment by thomasconner** [comment]
@ManuelFernando Please take a look when you have a chance. Thanks

**Comment by thomasconner** [comment]
@ManuelFernando Can you take a look at this PR?

**Comment by ManuelFernando** [comment]
@thomasconner I’ll check it, can you give me information about what environment are you using, this is very important for me

**Comment by thomasconner** [comment]
@ManuelFernando What do you mean by environment? This change is related to [NativeScript](https://www.nativescript.org).

**Comment by ManuelFernando** [comment]
@thomasconner yes about your nativescript environment

**Comment by thomasconner** [comment]
I am using NativeScript 5.0 and running the app on iOS 12 and Android 7.

**Pull request merged**
