### PR TITLE
fix: create gzipped publish artifacts

### PR DESCRIPTION
**Pull request by are**
feat: TypeScript migration

Added a TypeScript build chain and moved from webpack to rollup.

feat: Event Engine initial implementation

Added an initial implementation of Event Engine.

### CODE REVIEW

**Comment by are** [comment]
@client-engineering-bot release as v5.0.1

**Comment by are** [comment]
@client-engineering-bot release as v6.0.0

**Review by parfeon — APPROVED** [review]
LGTM!

**Comment by are** [comment]
@client-engineering-bot release as v6.0.0

**Pull request merged**
